name: MIXER
plugin: ./lib/plugins/basic
siteUrl: https://mixer.com/
urlback: ""
enable: true
m3u8fetch: scripts/m3u8_youtubedl.sh
recorder: scripts/record_ffmpeg.sh
scanInterval: 300
batchSize: 5
streamers:
  - britni
